import type { FieldDef } from "@/components/config-sections";

export const VISION_FIELDS: FieldDef[] = [
  {
    key: "vision_strategy",
    label: "Strategy",
    kind: "select",
    options: [
      { value: "never", label: "Never" },
      { value: "catalog", label: "Catalog" },
      { value: "always", label: "Always" },
    ],
    restartRequired: true,
    required: true,
  },
  {
    key: "vision_model",
    label: "Model",
    kind: "select",
    description: "Vision-capable model from /v1/models/info (supports_vision = true).",
    restartRequired: true,
    required: true,
  },
  {
    key: "vision_prompt",
    label: "Prompt",
    kind: "textarea",
    restartRequired: true,
    required: true,
  },
  {
    key: "vision_prompt_version",
    label: "Prompt Version",
    kind: "number",
    restartRequired: true,
    required: true,
    min: 1,
  },
  {
    key: "vision_max_images",
    label: "Max Images",
    kind: "number",
    restartRequired: true,
    required: true,
    min: 1,
    max: 100,
  },
  {
    key: "vision_max_description_tokens",
    label: "Max Description Tokens",
    kind: "number",
    restartRequired: true,
    required: true,
    min: 1,
    max: 200000,
  },
  {
    key: "vision_reasoning_effort",
    label: "Reasoning Effort",
    kind: "select",
    description: "Reasoning effort for vision model. null = use model default.",
    options: [
      { value: "", label: "Default (null)" },
      { value: "none", label: "None" },
      { value: "low", label: "Low" },
      { value: "medium", label: "Medium" },
      { value: "high", label: "High" },
    ],
    nullable: true,
    restartRequired: true,
  },
  {
    key: "vision_timeout_ms",
    label: "Timeout",
    kind: "number",
    restartRequired: true,
    required: true,
    min: 1000,
    suffix: "ms",
  },
  {
    key: "vision_cache_size",
    label: "Cache Size",
    kind: "number",
    restartRequired: true,
    required: true,
    min: 100,
  },
  {
    key: "vision_cache_ttl_ms",
    label: "Cache TTL",
    kind: "number",
    description: "Time-to-live for vision description cache entries.",
    restartRequired: true,
    min: 1000,
    suffix: "ms",
  },
  {
    key: "vision_cache_max_rows",
    label: "Cache Max Rows",
    kind: "number",
    description: "Maximum number of rows in the vision persistent cache.",
    restartRequired: true,
    min: 100,
  },
  {
    key: "vision_persistent_cache",
    label: "Persistent Cache",
    kind: "boolean",
    description: "Whether vision cache persists to disk.",
    restartRequired: true,
  },
  {
    key: "vision_concurrency",
    label: "Concurrency",
    kind: "number",
    restartRequired: true,
    required: true,
    min: 1,
    max: 20,
  },
  {
    key: "vision_max_dimension",
    label: "Max Dimension",
    kind: "number",
    description: "Maximum image dimension (width or height) before downscaling.",
    restartRequired: true,
    min: 256,
    max: 8192,
    suffix: "px",
  },
  {
    key: "vision_jpeg_quality",
    label: "JPEG Quality",
    kind: "number",
    description: "JPEG encoding quality for image preprocessing (1–100).",
    restartRequired: true,
    min: 1,
    max: 100,
  },
  {
    key: "vision_image_format",
    label: "Image Format",
    kind: "select",
    description: "Output image format for preprocessing.",
    options: [
      { value: "jpeg", label: "JPEG" },
      { value: "png", label: "PNG" },
    ],
    restartRequired: true,
  },
  {
    key: "vision_image_detail",
    label: "Image Detail",
    kind: "select",
    description: "OpenAI-style image detail level.",
    options: [
      { value: "auto", label: "Auto" },
      { value: "low", label: "Low" },
      { value: "high", label: "High" },
    ],
    restartRequired: true,
  },
  {
    key: "vision_api_key",
    label: "API Key",
    kind: "password",
    restartRequired: true,
  },
  {
    key: "vision_force_intercept_capable",
    label: "Force Intercept Capable",
    kind: "boolean",
    restartRequired: true,
  },
];
