import { badgeInfo, badgeSuccess, badgeWarning } from "@/lib/badge-colors";
import { statusClass } from "@/lib/format";
import { Badge } from "./ui/badge";
import { Tooltip, TooltipContent, TooltipTrigger } from "./ui/tooltip";

const badgeConfig: Record<
  ReturnType<typeof statusClass>,
  { variant: "default" | "secondary" | "outline" | "destructive"; className?: string }
> = {
  ok: { variant: "secondary", className: badgeSuccess },
  info: { variant: "secondary", className: badgeInfo },
  warn: { variant: "secondary", className: badgeWarning },
  err: { variant: "destructive" },
  "": { variant: "secondary" },
};

const STATUS_TIP: Record<string, string> = {
  ok: "2xx/3xx success",
  info: "3xx redirection",
  warn: "4xx client error",
  err: "5xx server error",
  "": "No response yet",
};

interface StatusBadgeProps {
  status: number | null;
  statusSource?: "upstream" | "gate" | null;
  gateReason?: string | null;
  size?: "default" | "sm";
}

export function StatusBadge({
  status,
  statusSource = null,
  gateReason = null,
  size = "default",
}: StatusBadgeProps) {
  const klass = statusClass(status);
  const cfg = badgeConfig[klass];
  const tip = STATUS_TIP[klass];
  const isGate = statusSource === "gate";
  const label = status == null ? "—" : `${status}${isGate ? "-gate" : ""}`;
  const tooltipText =
    isGate && gateReason
      ? `HTTP ${status} — generated by gate (not upstream): ${gateReason}`
      : `HTTP ${label} — ${tip}`;

  return (
    <Tooltip>
      <TooltipTrigger render={<span className="inline-flex" />}>
        <Badge variant={cfg.variant} size={size} className={cfg.className}>
          {label}
        </Badge>
      </TooltipTrigger>
      <TooltipContent side="top">{tooltipText}</TooltipContent>
    </Tooltip>
  );
}
