// The default config written on first run.

import type { RawConfig } from "./types.js";

/** The default config written on first run. */
const DEFAULT_CONFIG: RawConfig = {
  port: 1945,
  max_captures: 200,
  db_path: "./umans-gate.db",
  idle_timeout: 255,
  upstream_protocol: "http1.1",
  stamp_claude_code_enabled: false,
  stamp_reasoning_effort_enabled: false,
  warmer_enabled: true,
  warmer_interval_ms: 20000,
  umans_api_key: "",
  dashboard_token: "",
  usage_refresh_ms: 60000,
  usage_history_enabled: true,
  usage_raw_retention_days: 7,
  usage_gap_threshold_minutes: 60,
  models_refresh_ms: 3600000,
  concurrency_hard_cap: 16,
  concurrency_soft_limit: 8,
  use_hard_cap: false,
  rate_limit_requests: 0,
  queue_timeout_ms: 30000,
  max_queue_depth: 256,
  release_cooldown_ms: 1000,
  breaker_threshold: 5,
  breaker_window_ms: 300000,
  breaker_cooldown_ms: 60000,
  vision_strategy: "catalog",
  vision_model: "umans-flash",
  vision_prompt:
    "You are an expert visual analyst with perfect vision and meticulous attention to detail. Your task is to produce an exhaustive, accurate description of an image for a downstream text-only language model that cannot see the image.\n\nStructure your description as:\n\n1. IMAGE TYPE: What kind of image is this (photograph, screenshot, diagram, chart, illustration, document scan, UI mockup, etc.)?\n\n2. OVERALL CONTENT: A comprehensive summary of everything visible.\n\n3. TEXT/OCR: Transcribe ALL visible text exactly as written, preserving:\n   - Original spelling, formatting, and hierarchy\n   - Line breaks and spatial layout\n   - Numbers, codes, identifiers, and labels\n   - Captions, watermarks, signatures\n   If text is partially visible, transcribe what you can and mark gaps with [...].\n\n4. VISUAL ELEMENTS: Describe in detail:\n   - Objects, people, and their positions/relationships\n   - Colors, shapes, textures\n   - Spatial layout and composition\n   - UI elements (buttons, menus, fields, tabs) if a screenshot\n\n5. DATA/CHARTS: If charts, tables, or data visualizations are present:\n   - Chart type and axes\n   - Data values, ranges, and trends\n   - Table structure and cell contents\n\n6. CONTEXTUAL CLUES: Date/time indicators, language, cultural context, technical domain indicators.\n\n7. QUALITY NOTES: Any blur, artifacts, obstructions, or ambiguity.\n\nRules:\n- Describe what is VISIBLE, not what you infer.\n- Be exhaustive: omit nothing visible. When in doubt, include it.\n- For uncertain elements, state your uncertainty rather than guessing.\n- Do not summarize or abbreviate.\n- Output only the description, no preamble.",
  vision_prompt_version: 2,
  vision_max_images: 5,
  vision_max_description_tokens: 4096,
  vision_reasoning_effort: "none",
  vision_timeout_ms: 0,
  vision_cache_size: 1000,
  vision_cache_ttl_ms: 604800000,
  vision_cache_max_rows: 10000,
  vision_persistent_cache: true,
  vision_concurrency: 1,
  vision_max_dimension: 2048,
  vision_jpeg_quality: 92,
  vision_image_format: "png",
  vision_image_detail: "high",
  vision_intent_strategy: "auto",
  vision_decomposition_enabled: true,
  vision_decomposition_timeout_ms: 3000,
  vision_crafting_timeout_ms: 3000,
  vision_adjacent_text_max_chars: 500,
  vision_recent_messages_count: 6,
  vision_system_prompt_max_chars: 1000,
  concurrency_main_reservation: 1,
  concurrency_vision_reservation: 1,
  capture_body_max_bytes: 10_000_000,
  queue_max_depth: 100,
  ws_backpressure_limit: 1_048_576,
  ws_close_on_backpressure_limit: true,
  vision_pending_max_batch: 50,
  compression_enabled: true,
  upstream_timeout_ms: 300000,
  experiment_rewrite_ids: false,
  experiment_rewrite_ttl_ms: 3600000,
  experiment_strip_omo_reminder: false,
};

export { DEFAULT_CONFIG };
