#!/usr/bin/env bun
// scripts/embed-assets.ts
// Reads dashboard/dist/ recursively, generates src/embedded-assets.ts with
// `import "./../dashboard/dist/<file>" with { type: "file" }` for each asset.
// Run this AFTER `bun run build:dashboard` and BEFORE `bun build --compile`.

import { existsSync, readdirSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const ROOT = resolve(import.meta.dir, "..");
const DASHBOARD_DIST = join(ROOT, "dashboard", "dist");
const OUTPUT = join(ROOT, "src", "embedded-assets.ts");

if (!existsSync(DASHBOARD_DIST)) {
  console.error("dashboard/dist/ not found. Run: cd dashboard && bun run build");
  process.exit(1);
}

// Collect all files in dashboard/dist/ recursively
const files: string[] = [];
function walk(dir: string, base: string = dir) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      walk(fullPath, base);
    } else {
      // Store path relative to dashboard/dist/
      files.push(fullPath.slice(base.length + 1).replace(/\\/g, "/"));
    }
  }
}
walk(DASHBOARD_DIST);

if (files.length === 0) {
  console.error("No files found in dashboard/dist/");
  process.exit(1);
}

// Generate import statements
const imports: string[] = [];
for (const file of files) {
  // Use relative path from src/ to dashboard/dist/
  imports.push(`import "./../dashboard/dist/${file}" with { type: "file" };`);
}

const content = `// AUTO-GENERATED by scripts/embed-assets.ts — DO NOT EDIT.
// This file imports dashboard assets so they get embedded into compiled executables.
// In dev mode, these resolve to filesystem paths.
// In compiled mode, Bun.embeddedFiles exposes them as Blobs.
${imports.join("\n")}

export const EMBEDDED_ASSET_PATHS = ${JSON.stringify(files)};
`;

writeFileSync(OUTPUT, content);
console.log(`✅ Generated ${OUTPUT} with ${imports.length} embedded asset imports`);
