// AUTO-GENERATED by scripts/embed-assets.ts — DO NOT EDIT.
// This file imports dashboard assets so they get embedded into compiled executables.
// In dev mode, these resolve to filesystem paths.
// In compiled mode, Bun.embeddedFiles exposes them as Blobs.
import "./../dashboard/dist/index.html" with { type: "file" };
import "./../dashboard/dist/assets/index-DFhG4t-C.css" with { type: "file" };
import "./../dashboard/dist/assets/headers-viewer-oZosQju7.js.map" with { type: "file" };
import "./../dashboard/dist/assets/vision-calls-CvRPnxdD.js" with { type: "file" };
import "./../dashboard/dist/assets/geist-latin-wght-normal-BgDaEnEv.woff2" with { type: "file" };
import "./../dashboard/dist/assets/clear-confirm-dialog-CuYJoWO8.js" with { type: "file" };
import "./../dashboard/dist/assets/vendor-DtX4s2-2.css" with { type: "file" };
import "./../dashboard/dist/assets/json-viewer-CSkdkH8P.js.map" with { type: "file" };
import "./../dashboard/dist/assets/economics-tab-BmJ9pYcp.js" with { type: "file" };
import "./../dashboard/dist/assets/sheet-BeCsFJbV.js" with { type: "file" };
import "./../dashboard/dist/assets/alert-dialog-B8_aJXpj.js" with { type: "file" };
import "./../dashboard/dist/assets/clear-confirm-dialog-CuYJoWO8.js.map" with { type: "file" };
import "./../dashboard/dist/assets/use-polling-resource-Bzwd9IFv.js.map" with { type: "file" };
import "./../dashboard/dist/assets/headers-viewer-oZosQju7.js" with { type: "file" };
import "./../dashboard/dist/assets/select-CsFcKotz.js" with { type: "file" };
import "./../dashboard/dist/assets/geist-vietnamese-wght-normal-6IgcOCM7.woff2" with { type: "file" };
import "./../dashboard/dist/assets/performance-meter-B3SvMIyI.js" with { type: "file" };
import "./../dashboard/dist/assets/economics-tab-BmJ9pYcp.js.map" with { type: "file" };
import "./../dashboard/dist/assets/use-models-p4yDcMO_.js.map" with { type: "file" };
import "./../dashboard/dist/assets/vendor-react-BPcdhvsf.js.map" with { type: "file" };
import "./../dashboard/dist/assets/select-CsFcKotz.js.map" with { type: "file" };
import "./../dashboard/dist/assets/vendor-react-BPcdhvsf.js" with { type: "file" };
import "./../dashboard/dist/assets/mode-toggle-B5vsM8uT.js.map" with { type: "file" };
import "./../dashboard/dist/assets/sse-viewer-CzDWGfHy.js" with { type: "file" };
import "./../dashboard/dist/assets/use-polling-resource-Bzwd9IFv.js" with { type: "file" };
import "./../dashboard/dist/assets/config-tab-C7aMZZH0.js" with { type: "file" };
import "./../dashboard/dist/assets/index-DFV-zVQq.js.map" with { type: "file" };
import "./../dashboard/dist/assets/geist-cyrillic-ext-wght-normal-DjL33-gN.woff2" with { type: "file" };
import "./../dashboard/dist/assets/performance-meter-B3SvMIyI.js.map" with { type: "file" };
import "./../dashboard/dist/assets/use-capture-done-listener-9r7M4Gia.js.map" with { type: "file" };
import "./../dashboard/dist/assets/use-capture-done-listener-9r7M4Gia.js" with { type: "file" };
import "./../dashboard/dist/assets/sheet-BeCsFJbV.js.map" with { type: "file" };
import "./../dashboard/dist/assets/sonner-BCuD8EZU.js" with { type: "file" };
import "./../dashboard/dist/assets/models-tab-DIiJfxL5.js" with { type: "file" };
import "./../dashboard/dist/assets/models-tab-DIiJfxL5.js.map" with { type: "file" };
import "./../dashboard/dist/assets/index-DFV-zVQq.js" with { type: "file" };
import "./../dashboard/dist/assets/vision-calls-CvRPnxdD.js.map" with { type: "file" };
import "./../dashboard/dist/assets/geist-latin-ext-wght-normal-DC-KSUi6.woff2" with { type: "file" };
import "./../dashboard/dist/assets/vendor-Dhq7b7GR.js" with { type: "file" };
import "./../dashboard/dist/assets/use-models-p4yDcMO_.js" with { type: "file" };
import "./../dashboard/dist/assets/sse-viewer-CzDWGfHy.js.map" with { type: "file" };
import "./../dashboard/dist/assets/mode-toggle-B5vsM8uT.js" with { type: "file" };
import "./../dashboard/dist/assets/alert-dialog-B8_aJXpj.js.map" with { type: "file" };
import "./../dashboard/dist/assets/json-viewer-CSkdkH8P.js" with { type: "file" };
import "./../dashboard/dist/assets/geist-cyrillic-wght-normal-BEAKL7Jp.woff2" with { type: "file" };
import "./../dashboard/dist/assets/config-tab-C7aMZZH0.js.map" with { type: "file" };
import "./../dashboard/dist/assets/sonner-BCuD8EZU.js.map" with { type: "file" };
import "./../dashboard/dist/assets/vendor-Dhq7b7GR.js.map" with { type: "file" };

export const EMBEDDED_ASSET_PATHS = ["index.html","assets/index-DFhG4t-C.css","assets/headers-viewer-oZosQju7.js.map","assets/vision-calls-CvRPnxdD.js","assets/geist-latin-wght-normal-BgDaEnEv.woff2","assets/clear-confirm-dialog-CuYJoWO8.js","assets/vendor-DtX4s2-2.css","assets/json-viewer-CSkdkH8P.js.map","assets/economics-tab-BmJ9pYcp.js","assets/sheet-BeCsFJbV.js","assets/alert-dialog-B8_aJXpj.js","assets/clear-confirm-dialog-CuYJoWO8.js.map","assets/use-polling-resource-Bzwd9IFv.js.map","assets/headers-viewer-oZosQju7.js","assets/select-CsFcKotz.js","assets/geist-vietnamese-wght-normal-6IgcOCM7.woff2","assets/performance-meter-B3SvMIyI.js","assets/economics-tab-BmJ9pYcp.js.map","assets/use-models-p4yDcMO_.js.map","assets/vendor-react-BPcdhvsf.js.map","assets/select-CsFcKotz.js.map","assets/vendor-react-BPcdhvsf.js","assets/mode-toggle-B5vsM8uT.js.map","assets/sse-viewer-CzDWGfHy.js","assets/use-polling-resource-Bzwd9IFv.js","assets/config-tab-C7aMZZH0.js","assets/index-DFV-zVQq.js.map","assets/geist-cyrillic-ext-wght-normal-DjL33-gN.woff2","assets/performance-meter-B3SvMIyI.js.map","assets/use-capture-done-listener-9r7M4Gia.js.map","assets/use-capture-done-listener-9r7M4Gia.js","assets/sheet-BeCsFJbV.js.map","assets/sonner-BCuD8EZU.js","assets/models-tab-DIiJfxL5.js","assets/models-tab-DIiJfxL5.js.map","assets/index-DFV-zVQq.js","assets/vision-calls-CvRPnxdD.js.map","assets/geist-latin-ext-wght-normal-DC-KSUi6.woff2","assets/vendor-Dhq7b7GR.js","assets/use-models-p4yDcMO_.js","assets/sse-viewer-CzDWGfHy.js.map","assets/mode-toggle-B5vsM8uT.js","assets/alert-dialog-B8_aJXpj.js.map","assets/json-viewer-CSkdkH8P.js","assets/geist-cyrillic-wght-normal-BEAKL7Jp.woff2","assets/config-tab-C7aMZZH0.js.map","assets/sonner-BCuD8EZU.js.map","assets/vendor-Dhq7b7GR.js.map"];
